<a href="https://colab.research.google.com/github/AllanGonzales/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FINAL EXAM

Problem 1


In [8]:
A = np.array ([[1,1,1],[1,0,4],[0,0,5]])
print(f'Matrix A:\n {A}')
print()
B = np.array ([[89],[89],[95]])
print(f'Matrix B:\n {A}')
C = np.linalg.inv(A).dot(B)
print(f'\nInverse of Matrix  A:\n {C}')


Matrix A:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix B:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Inverse of Matrix  A:
 [[13.]
 [57.]
 [19.]]


Problem 2

In [6]:
A = np.array ([[3,-1,1],[9,3,-3],[-12,4,-4]])
print('Matrix A:\n {A}')

#since it is a singular matrix , we cannot inverse it but we can still show the output

inv_A = np.linalg.pinv(A)
print(f'\nInverse of Matrix A:\n {inv_A}')

B = np.array ([[5],[10],[-20]])
print(f'Matrix A:\n {A}')

X = np.dot(inv_A, B)
print(f'\nDot product:\n{X}')

C= np.dot(A, X)
print(f'\nChecking :\n{C}')


Matrix A:
 {A}

Inverse of Matrix A:
 [[ 0.00980392  0.05555556 -0.03921569]
 [-0.01470588  0.08333333  0.05882353]
 [ 0.01470588 -0.08333333 -0.05882353]]
Matrix A:
 [[  3  -1   1]
 [  9   3  -3]
 [-12   4  -4]]

Dot product:
[[ 1.38888889]
 [-0.41666667]
 [ 0.41666667]]

Checking :
[[  5.]
 [ 10.]
 [-20.]]


Problem 3

In [2]:
import numpy as np
from numpy.linalg import eig

A = np.array ([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print (A,"\n")
w,v= np.linalg.eig(A)

print("The eigenvalues are: \n",w)
print("The eigenvectors are: \n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalues are: 
 [-1.  3.  2.]
The eigenvectors are: 
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
