<a href="https://colab.research.google.com/github/AllanGonzales/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Midterm Exam***

Question 1


In [1]:
import numpy as np
A = np.array([[5,4,3,2,1],[1,2,3,4,5],[10,9,8,7,6],[6,7,8,9,10],[1,3,5,7,9]])
print(A)

[[ 5  4  3  2  1]
 [ 1  2  3  4  5]
 [10  9  8  7  6]
 [ 6  7  8  9 10]
 [ 1  3  5  7  9]]


Question 2

In [5]:
A = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]])
print(A)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


Question 3

In [13]:
A =np.array([[6,1,6],[1,5,2],[6,2,7]])
print(A)
print("/n")
#prints transpose matrix

print(np.transpose(A))

[[6 1 6]
 [1 5 2]
 [6 2 7]]
/n
[[6 1 6]
 [1 5 2]
 [6 2 7]]


Question 4

In [2]:
A=np.array(([[1,2,3],[2,3,3],[3,4,-2]]))
B=(np.linalg.inv(A))
print(B)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5

In [6]:
A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


Question 6

In [11]:
c = np.array([[5,4,1],[10,9,4],[10,13,15]])
inv_c = np.linalg.inv(c)
print (c)
print ()
print (inv_c)

d = np.array([[3.4],[8.8],[19.2]])

x = np.dot(inv_c, d)
print ("roots =")
print (x)

z = np.dot(c,x) #checking
print('checking =')
print (z)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
roots =
[[0.2]
 [0.4]
 [0.8]]
checking =
[[ 3.4]
 [ 8.8]
 [19.2]]
