<a href="https://colab.research.google.com/github/AllanGonzales/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1 (A)

In [3]:
import numpy as np
W = np.array([[1,-3],[2,-2],[3,1]])
print("Vector W is", W)

Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]


In [7]:
Y = np.array([[1,2,0],[0,-1,2]])
print("Vector Y is", Y)

Vector Y is [[ 1  2  0]
 [ 0 -1  2]]


In [5]:
print(np.dot(W,Y))

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


Problem 1 (B)

In [10]:
Z = np.array([[0,1],[2,3]])
Z = np.array([[0,1],[2,3]])
print((Z+Z))

[[0 2]
 [4 6]]


Problem 1 (C)


In [15]:
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print("Vector X is", X)
print()
print(3*X)




Vector X is [[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


Problem 2 A



In [16]:
Y = np.array([[1,2,0],[0,-1,2]])
W = np.array([[1,-3],[2,-2],[3,1]])
print(np.dot(Y,W)^2)

[[ 7 -5]
 [ 6  6]]


Problem 2 B

In [17]:
R = np.dot(W,Y)
R

array([[ 1,  5, -6],
       [ 2,  6, -4],
       [ 3,  5,  2]])

In [18]:
print(np.subtract(R,X))

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


Problem 2 C

In [19]:
Y = np.array([[1,2,0],[0,-1,2]])
W = np.array([[1,-3],[2,-2],[3,1]])
Z = np.array([[0,1],[2,3]])
print(np.dot(Y,W)-Z^2)

[[ 7 -6]
 [ 0  3]]
